### ISSUE TITLE
Protocols not properly loaded?

### ISSUE THREAD

**Issue by mikl** [adam12/ecto_network#16] opened 2019-10-15 11:41 UTC
I’m not sure if I’m doing something wrong, but if I try to render an address in a .leex template (eg. `<%= @record.address %>`), I get this error:

```
protocol Phoenix.HTML.Safe not implemented for %Postgrex.INET{address: {206, 22, 87, 1}, netmask: 32} of type Postgrex.INET (a struct). This protocol is implemented for the following type(s): Decimal, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Rendered, Time, Integer, Tuple, List, DateTime, NaiveDateTime, Float, Atom, Phoenix.HTML.Form, BitString, Date
```

Changing it to `<%= to_string(@record.address) %>` yields a slightly different error:

```
protocol String.Chars not implemented for %Postgrex.INET{address: {216, 24, 57, 1}, netmask: 32} of type Postgrex.INET (a struct). This protocol is implemented for the following type(s): Postgrex.Copy, Postgrex.Query, Decimal, Float, DateTime, Time, List, Version.Requirement, Atom, Integer, Version, Date, BitString, NaiveDateTime, URI
```

If I change the code to `<%= EctoNetwork.INET.decode(@record.address) %>`, it does render correctly, so I have a usable workaround.

I see the protocols defined here: https://github.com/adam12/ecto_network/blob/master/lib/ecto_network/inet.ex#L102 - so I’m a bit confused. I tried adding `require EctoNetwork.INET` to my view, but that makes no difference as far as I can tell?

Is there some step I missed to get the protocol implementations to load correctly? I have a umbrella app, if that makes any difference, and the relevant package versions are:

```
  db_connection 2.1.1
  ecto 3.2.1
  ecto_network 1.1.0
  ecto_sql 3.2.0
  phoenix 1.4.10
  phoenix_ecto 4.0.0
  phoenix_html 2.13.3
  postgrex 0.15.1
```

I’m using Elixir 1.9.2, Erlang/OTP 22.1.3 on macOS 10.15.

**Comment by adam12** [comment] 2019-10-15 15:02
I'll have to look into this and get back to you. Are you able to make a cloneable example that demonstrates the issue to save me some time?

I thought we were testing the protocol implementations for `String.Chars` and `Phoenix.HTML.Safe` but it looks like were not.

**Comment by mikl** [comment] 2019-10-15 15:29
I’ll try setting up an example.

**Comment by mikl** [comment] 2019-10-16 23:57
Very strange, I cannot reproduce this in a simplified example. I have the exact same versions of everything important, yet one project loads the protocols just fine, and the other one just doesn't, very confusing 😞

**Comment by adam12** [comment] 2019-10-17 03:21
I'll try to reproduce as well but everything looks right as far as I can tell.

Let me know if anything changes on your end.

**Comment by adam12** [comment] 2019-11-01 03:35
I'm going to close this for now. If you're able to reproduce it for me to debug, please re-open.

**Closed as completed by adam12** 2019-11-01 03:35 UTC
