### ISSUE TITLE
function embed_as/1 required by behaviour Ecto.Type is not implemented

### ISSUE THREAD

**Issue by ghost** [adam12/ecto_network#17] opened 2019-10-21 11:01 UTC
With ecto `3.2` version `@behaviour Ecto.Type` should implement `embed_as/1` and equal?/2 or replace `@behaviour Ecto.Type` with `use Ecto.Type`

**Comment by adam12** [comment] 2019-10-21 13:29
Thanks for the report. This looks to be a duplicate of #14

**Closed as completed by adam12** 2019-10-21 13:29 UTC

**Comment by mikl** [comment] 2019-12-11 00:04
Just in case anyone else runs in to this, I had some strange corruption in my build files. `mix clean && mix deps.clean` fixed it.
